CREATE TABLE USUARIO(
IDUSUARIO INT PRIMARY KEY IDENTITY(1,1),
CORREO VARCHAR(100),
CLAVE VARCHAR(500)
)

DROP TABLE Concierto

CREATE PROC SP_REGISTRARUSUARIO(
@CORREO VARCHAR(100),
@CLAVE VARCHAR(500),
@REGISTRADO BIT OUTPUT,
@MENSAJE VARCHAR(100) OUTPUT
)
AS
	BEGIN
		IF(not exists(SELECT * FROM USUARIO WHERE CORREO = @CORREO))
		BEGIN
			INSERT INTO USUARIO(CORREO,CLAVE) VALUES (@CORREO, @CLAVE)
			SET @REGISTRADO = 1
			SET @MENSAJE = 'USUARIO REGISTRADO'
		END
		ELSE
		BEGIN
			SET @REGISTRADO = 0
			SET @MENSAJE = 'CORREO YA EXISTE'
		END
END

ALTER PROC SP_VALIDARUSUARIO(
@CORREO VARCHAR(100),
@CLAVE VARCHAR(500)
)
AS
	BEGIN
		IF(exists(SELECT * FROM USUARIO WHERE CORREO = @CORREO AND CLAVE = @CLAVE))
			SELECT IDUSUARIO FROM USUARIO WHERE CORREO = @CORREO AND CLAVE = @CLAVE
		ELSE
			SELECT '0'
	END

DECLARE @REGISTRADO BIT, @MENSAJE VARCHAR(100)

EXEC SP_REGISTRARUSUARIO 'ADMIN@GMAIL.COM', 'TEST123', @REGISTRADO OUTPUT, @MENSAJE OUTPUT

SELECT @REGISTRADO
SELECT @MENSAJE

SELECT * FROM USUARIO

EXEC SP_VALIDARUSUARIO 'ADMINCONCIERTO@GMAIL.COM', '56a7010456b474aeee111f3b7336581fb0a99129d426cf51903efbdfd629f008'


CREATE PROC SP_REGISTRARCONCIERTO(
@Nombre_Banda VARCHAR(50),
@Genero_Musical VARCHAR(50),
@Fecha_Concierto DATE,
@Hora_Concierto TIME,
@Pais VARCHAR(47),
@Direccion_Concierto VARCHAR(168),
@REGISTRADO BIT OUTPUT,
@MENSAJE VARCHAR(100) OUTPUT
)
AS
	BEGIN
		IF(not exists(SELECT * FROM Concierto WHERE Nombre_Banda = @Nombre_Banda AND Genero_Musical = @Genero_Musical AND Fecha_Concierto = @Fecha_Concierto AND Hora_Concierto = @Hora_Concierto AND Pais = @Pais AND Direccion_Concierto = @Direccion_Concierto ))
		BEGIN
			INSERT INTO Concierto(Nombre_Banda,Genero_Musical,Fecha_Concierto,Hora_Concierto,Pais,Direccion_Concierto) VALUES (@Nombre_Banda, @Genero_Musical, @Fecha_Concierto, @Hora_Concierto, @Pais, @Direccion_Concierto)
			SET @REGISTRADO = 1
			SET @MENSAJE = 'CONCIERTO REGISTRADO'
		END
		ELSE
		BEGIN
			SET @REGISTRADO = 0
			SET @MENSAJE = 'CONCIERTO YA EXISTE'
		END
END

DECLARE @REGISTRADO BIT, @MENSAJE VARCHAR(100)

EXEC SP_REGISTRARCONCIERTO 'Ca7riel y Paco Amoroso','Pop', "2025-03-31","21:00:00",'Costa Rica','El mercadito, Barrio La California, San José', @REGISTRADO OUTPUT, @MENSAJE OUTPUT

SELECT * FROM Concierto