//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_progra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concierto
    {
        public int ID { get; set; }
        public string Nombre_Banda { get; set; }
        public string Genero_Musical { get; set; }
        public System.DateTime Fecha_Concierto { get; set; }
        public System.TimeSpan Hora_Concierto { get; set; }
        public string Pais { get; set; }
        public string Direccion_Concierto { get; set; }
    }
}
