//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_progra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConciertosEntities1 : DbContext
    {
        public ConciertosEntities1()
            : base("name=ConciertosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concierto> Concierto { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int SP_REGISTRARUSUARIO(string cORREO, string cLAVE, ObjectParameter rEGISTRADO, ObjectParameter mENSAJE)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRARUSUARIO", cORREOParameter, cLAVEParameter, rEGISTRADO, mENSAJE);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_VALIDARUSUARIO(string cORREO, string cLAVE)
        {
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_VALIDARUSUARIO", cORREOParameter, cLAVEParameter);
        }
    
        public virtual int SP_REGISTRARCONCIERTO(string nombre_Banda, string genero_Musical, Nullable<System.DateTime> fecha_Concierto, Nullable<System.TimeSpan> hora_Concierto, string pais, string direccion_Concierto, ObjectParameter rEGISTRADO, ObjectParameter mENSAJE)
        {
            var nombre_BandaParameter = nombre_Banda != null ?
                new ObjectParameter("Nombre_Banda", nombre_Banda) :
                new ObjectParameter("Nombre_Banda", typeof(string));
    
            var genero_MusicalParameter = genero_Musical != null ?
                new ObjectParameter("Genero_Musical", genero_Musical) :
                new ObjectParameter("Genero_Musical", typeof(string));
    
            var fecha_ConciertoParameter = fecha_Concierto.HasValue ?
                new ObjectParameter("Fecha_Concierto", fecha_Concierto) :
                new ObjectParameter("Fecha_Concierto", typeof(System.DateTime));
    
            var hora_ConciertoParameter = hora_Concierto.HasValue ?
                new ObjectParameter("Hora_Concierto", hora_Concierto) :
                new ObjectParameter("Hora_Concierto", typeof(System.TimeSpan));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var direccion_ConciertoParameter = direccion_Concierto != null ?
                new ObjectParameter("Direccion_Concierto", direccion_Concierto) :
                new ObjectParameter("Direccion_Concierto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REGISTRARCONCIERTO", nombre_BandaParameter, genero_MusicalParameter, fecha_ConciertoParameter, hora_ConciertoParameter, paisParameter, direccion_ConciertoParameter, rEGISTRADO, mENSAJE);
        }
    
        public virtual int SP_ELIMINARCONCIERTO(Nullable<int> iD, ObjectParameter eLIMINADO, ObjectParameter mENSAJE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARCONCIERTO", iDParameter, eLIMINADO, mENSAJE);
        }
    
        public virtual int SP_MODIFICARCONCIERTO(Nullable<int> iD, string nombre_Banda, string genero_Musical, Nullable<System.DateTime> fecha_Concierto, Nullable<System.TimeSpan> hora_Concierto, string pais, string direccion_Concierto, ObjectParameter mODIFICADO, ObjectParameter mENSAJE)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombre_BandaParameter = nombre_Banda != null ?
                new ObjectParameter("Nombre_Banda", nombre_Banda) :
                new ObjectParameter("Nombre_Banda", typeof(string));
    
            var genero_MusicalParameter = genero_Musical != null ?
                new ObjectParameter("Genero_Musical", genero_Musical) :
                new ObjectParameter("Genero_Musical", typeof(string));
    
            var fecha_ConciertoParameter = fecha_Concierto.HasValue ?
                new ObjectParameter("Fecha_Concierto", fecha_Concierto) :
                new ObjectParameter("Fecha_Concierto", typeof(System.DateTime));
    
            var hora_ConciertoParameter = hora_Concierto.HasValue ?
                new ObjectParameter("Hora_Concierto", hora_Concierto) :
                new ObjectParameter("Hora_Concierto", typeof(System.TimeSpan));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var direccion_ConciertoParameter = direccion_Concierto != null ?
                new ObjectParameter("Direccion_Concierto", direccion_Concierto) :
                new ObjectParameter("Direccion_Concierto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCONCIERTO", iDParameter, nombre_BandaParameter, genero_MusicalParameter, fecha_ConciertoParameter, hora_ConciertoParameter, paisParameter, direccion_ConciertoParameter, mODIFICADO, mENSAJE);
        }
    }
}
